import type { Metadata } from "next";
import styles from "./page.module.css";
import { WHATSAPP_NUMBER } from "@/lib/catalogue";

export const metadata: Metadata = { title: "Cahier Malin | Des vacances sans écran, pleines de découvertes", description: "Le cahier d’activités pour les enfants de 6 à 10 ans : jeux, maths amusantes, histoires, culture générale et coloriages." };
const whatsapp = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("Bonjour, je souhaite commander le Cahier des Vacances Malines pour mon enfant.")}`;
const features = [["🧮","Maths amusantes","Des calculs, suites et petits défis qui font travailler la logique sans ressembler aux devoirs."],["🌍","Culture générale","Le Cameroun, l’Afrique, les animaux et le monde expliqués avec des jeux courts et accessibles."],["📖","Histoires & valeurs","De mini-histoires captivantes, suivies d’une leçon simple à retenir et à partager en famille."],["🎨","Jeux & coloriages","Des labyrinthes, jeux d’observation et coloriages pour nourrir l’attention et l’imagination."]];
const faqs = [["Pour quel âge ?","Les activités sont pensées pour les enfants de 6 à 10 ans. Les plus jeunes peuvent être accompagnés sur les consignes, puis avancer seuls."],["Mon enfant peut-il l’utiliser seul ?","Oui. Les consignes sont courtes et visuelles. Un parent peut lancer la première activité, puis laisser l’enfant explorer à son rythme."],["Comment commander ?","Cliquez sur le bouton WhatsApp. Un message de commande est déjà préparé : il ne reste qu’à l’envoyer et à confirmer la livraison."]];

export default function CahierDesVacancesPage() { return <div className={styles.page}>
  <header className={styles.nav}><div className={styles.brand}>Cahier <span>Malin</span></div><nav className={styles.navlinks}><a href="#contenu">Le contenu</a><a href="#apercu">Aperçu</a><a href="#commander">Commander</a></nav></header>
  <main><section className={styles.hero}><div><div className={styles.eyebrow}>Pour des vacances intelligentes</div><h1>Moins d’écrans.<br/><em>Plus de découvertes.</em></h1><p>Un cahier d’activités complet qui occupe intelligemment votre enfant avec des jeux, des histoires, des maths et de la culture générale.</p><div className={styles.actions}><a className={styles.button} href={whatsapp} target="_blank" rel="noreferrer">Commander sur WhatsApp ↗</a><a className={`${styles.button} ${styles.secondary}`} href="#apercu">Voir l’intérieur</a></div></div><img className={styles.heroImage} src="https://cahier-vacances-malin.wooplans237.chatgpt.site/images/cahier-hero.png" alt="Cahier des Vacances Malines"/></section>
  <section id="contenu" className={styles.section}><div className={styles.sectionHead}><div className={styles.eyebrow}>Dans son cahier</div><h2>Chaque page lui donne envie d’aller plus loin.</h2><p>Les activités alternent pour garder l’enfant curieux, concentré et fier de progresser — sans pression scolaire.</p></div><div className={styles.grid}>{features.map(([icon,title,text]) => <article className={styles.card} key={title}><div className={styles.icon}>{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className={styles.cream}><div id="apercu" className={styles.section}><div className={styles.sectionHead}><div className={styles.eyebrow}>Un aperçu du contenu</div><h2>Un vrai moment de calme… qui lui fait du bien.</h2></div><img className={styles.spread} src="https://cahier-vacances-malin.wooplans237.chatgpt.site/images/cahier-spread.png" alt="Aperçu des pages du cahier"/></div></section>
  <section className={styles.proof}><div className={styles.proofInner}><div><div className={styles.eyebrow}>Pensé pour les enfants. Approuvé par les parents.</div><h2>Pendant qu’il joue, il apprend naturellement.</h2><p>Votre enfant exerce sa lecture, sa logique, son attention et sa créativité, à son propre rythme.</p><a className={styles.button} href={whatsapp} target="_blank" rel="noreferrer">Je veux ce cahier pour mon enfant</a></div><div className={styles.offer} id="commander"><div><h3>Le Cahier des Vacances Malines</h3><div className={styles.price}>9 900 FCFA</div><div className={styles.note}>Paiement à la livraison · Confirmation rapide sur WhatsApp</div></div><a className={styles.button} href={whatsapp} target="_blank" rel="noreferrer">Commander maintenant</a></div></div></section>
  <section className={`${styles.section} ${styles.faq}`}><div className={styles.eyebrow}>Une question ?</div><h2>Tout ce qu’un parent veut savoir.</h2>{faqs.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></main>
  <footer className={styles.footer}><h2>Les vacances commencent ici.</h2><a className={styles.button} href={whatsapp} target="_blank" rel="noreferrer">Commander sur WhatsApp ↗</a><p className={styles.note}>© 2026 Cahier Malin. Tous droits réservés.</p></footer><a className={styles.mobileCta} href={whatsapp} target="_blank" rel="noreferrer">Commander · 9 900 FCFA</a>
 </div>; }
